apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: clusters-1-resources
spec:
  targets:
    - ./cluster-1.yaml
    - ./carts-service.yaml
    - ./databases/postgresql.yaml
    - ./databases/oracle.yaml